package com.example;

public enum GameStatus {
    GAME_OVER,
    PAUSED,
    GAME_RUNNING,
    GAME_COMPLETED,
    LEVEL_COMPLETED,
    MAIN_SCREEN,
    LOGIN_SCREEN,
    SIGNUP_SCREEN,
    ABOUT_SCREEN,
    SETTING_SCREEN,
    MAIN_MENU_SCREEN,
    INTRO_SCREEN,
    LEVEL_TRANSITIONING,
    CONGRATULATIONS
}
